# Configuration:
rules:
  # Visit the https://regex101.com website and see the effect.
  # I recommend this website for writing and testing regular expressions.
  - name: "DEV"
    host_name: "regex101.com"
    reg_exp: "(?mi).*" # Regular expression, Golang style. See https://golang.org/pkg/regexp/
    location: "" # Not used in this mode.
    mode: 0 # See ./internal/core/config.go → RuleModePASS
    body: "" # Not used in this mode.
    type: "" # Not used in this mode.
    prevent_cache: false
    cors: false
    active: true # Set to `false` to disable the rule.
    show_matches: true # The `true` value shows the match in the logs (terminal)

    # Visit the https://jquery.com website and see the effect.
  - name: "jQuery"
    host_name: "code.jquery.com"
    reg_exp: '(?m)\/jquery.*\.js'
    location: "" # Not used in this mode.
    mode: 200 # See ./internal/core/config.go → RuleModeOK
    body: 'alert("[RtMoR] The script content has been changed!")'
    type: "text/javascript"
    prevent_cache: true
    cors: false
    active: true
    show_matches: true

    # Visit the https://reactjs.org website and see the effect.
  - name: "React"
    host_name: "unpkg.com"
    reg_exp: '(?m)\/babel\.min\.js$'
    location: "file:assets/fake.js" # The `/` separator works in Windows, Linux and MacOS.
    mode: 237 # See ./internal/core/config.go → RuleModeFile
    body: "" # Not used in this mode.
    type: "text/javascript"
    prevent_cache: true
    cors: true
    active: true
    show_matches: true

    # Visit the https://angularjs.org website and see the effect.
  - name: "Angular"
    host_name: "angularjs.org"
    reg_exp: '(?m)\/prettify\.min\.js$'
    location: "https://raw.githubusercontent.com/Adrosar/rtmor/develop/assets/fake.js" # The `/` separator works in Windows, Linux and MacOS.
    mode: 239 # See ./internal/core/config.go → RuleModeUrl
    body: "" # Not used in this mode.
    type: "text/javascript"
    prevent_cache: true
    cors: true
    active: true
    show_matches: true

    # Visit the https://en.wikipedia.org website and see the effect.
  - name: "Wiki"
    host_name: "en.wikipedia.org"
    reg_exp: '(?m)enwiki\.png$'
    location: "" # Not used in this mode.
    mode: 404 # See ./internal/core/config.go → RuleModeNotFound
    body: "" # Not used in this mode.
    type: "" # Not used in this mode.
    prevent_cache: false
    cors: false
    active: true
    show_matches: true

    # Visit the https://www.google.com website and see the effect.
  - name: "Google"
    host_name: "www.google.com"
    reg_exp: '(?m)^https?\:\/\/www\.google\.com(\:443)?/?$'
    location: "https://duckduckgo.com" # If `mode` is `307` then `location` must contain the URL.
    mode: 307 # See ./internal/core/config.go → RuleModeRedirect
    body: "" # Not used in this mode.
    type: "" # Not used in this mode.
    prevent_cache: true
    cors: true
    active: true
    show_matches: true

  # Visit the https://www.youtube.com website and see the effect.
  - name: "YouTube"
    host_name: "www.youtube.com"
    reg_exp: '(?mi).+\.js$'
    location: "" # Not used in this mode.
    mode: 700 # See ./internal/core/config.go → RuleModeNoCache
    body: "" # Not used in this mode.
    type: "" # Not used in this mode.
    prevent_cache: true # Not used in this mode.
    cors: true # Not used in this mode.
    active: true
    show_matches: true
