# Configuration:
rules:
  # Visit the https://regex101.com website and see the effect.
  # I recommend this website for writing and testing regular expressions.
  - name: "DEV"
    host_name: "regex101.com"
    reg_exp: ""
    location: ""
    mode: 600 # See ./internal/core/config.go → ShowURL
    body: ""
    type: ""
    active: true # Set to `false` to disable the rule.

    # Visit the https://jquery.com website and see the effect.
  - name: "jQuery"
    host_name: "code.jquery.com"
    reg_exp: '(?m)\/jquery.*\.js' # Regular expression, Golang style. See https://golang.org/pkg/regexp/
    location: ""
    mode: 211 # See ./internal/core/config.go → ContentRuleMode
    body: 'alert("Hello RtMoR")'
    type: "text/javascript"
    active: true

    # Visit the https://en.wikipedia.org website and see the effect.
  - name: "Wiki"
    host_name: "en.wikipedia.org"
    reg_exp: '(?m)enwiki\.png$'
    location: ""
    mode: 404 # See ./internal/core/config.go → BlockRuleMode
    body: ""
    type: ""
    active: true

    # Visit the https://www.google.com website and see the effect.
  - name: "Google"
    host_name: "www.google.com"
    reg_exp: '(?m)^https?\:\/\/www\.google\.com(\:443)?/?$'
    location: "https://duckduckgo.com"
    mode: 307 # See ./internal/core/config.go → RedirectRuleMode
    body: ""
    type: ""
    active: true
